#+TITLE: Project Scratch

* Paper focus
- PoseOFF is:
  - Easy to implement
  - Lightweight
  - Improves action classification accuracy
  - Improves early action recognition accuracy
- Importantly, a way to embed human early visual motion cues to allow the model to predict actions with fewer frames!
- Defining local regions of flow so as to allow prediction models to both the movement of keypoints, as well as the relationship with other point-anchored patches.

* Core ideas
- PoseOFF as an extraction method can provide comparable accuracy with fewer observed frames
- Higher action anticipation ability with minimal additional computational overheads
** Action classification
This is retrospective recognition, where the full action is observed, and the action has already occured or is complete.
** Action anticipation
Prediction of an action classification label before the action has fully unfolded, using only partial observations.


* Find citations:
- VR/AR applications for human action anticipation
- In particular, the role of early visual motion cues are well understood to offer predictive cues during human movement or action [CITE].


* TODO code/graphs:
- Test the inference speed between PoseOFF embedded models and base
- [[file:main.tex::subsubsec:obs_ratio][OBS ratio graph]]
  - May want to test out action 113 (cheers and drink) or 118???
- flowpose diagram refinement

* TODO Consistency
Ensure action anticipation is primary term used.
