#+TITLE: Project Scratch

* Paper focus
- PoseOFF is:
  - Easy to implement
  - Lightweight
  - Improves action classification accuracy
  - Improves early action recognition accuracy
- Importantly, a way to embed human early visual motion cues to allow the model to predict actions with fewer frames!
- Defining local regions of flow so as to allow prediction models to both the movement of keypoints, as well as the relationship with other point-anchored patches.

* Core ideas
- PoseOFF as an extraction method can provide comparable accuracy with fewer observed frames
- Higher action anticipation ability with minimal additional computational overheads
** Action classification
This is retrospective recognition, where the full action is observed, and the action has already occured or is complete.
** Action anticipation
Prediction of an action classification label before the action has fully unfolded, using only partial observations.


* TODO
- Test the inference speed between PoseOFF embedded models and base
- Tidy up references
- De-verbose paper sections introduction
- Set figures apart either above or at the bottom of the text
- Cut down to six pages!
