#+title: PoseOFF ROMAN 2026

* Document outline
** [[file:main.tex::Introduction][1 Introduction]]
** [[file:main.tex::\section{Related work}][2 Related work]]
*** [[file:main.tex::\subsection{Human Action][2.1 Human Action Anticipation for Interactive Systems]]
*** [[file:main.tex::\subsection{Skeleton-based][2.2 Skeleton-based Human Action Recognition]]
*** [[file:main.tex::\subsection{Motion-based][2.3 Motion-based and Multimodal Approaches]]
** [[file:main.tex::\section{Method}][3 Method]]
*** [[file:main.tex::\subsection{PoseOFF Rep][3.1 PoseOFF Representation]]
*** [[file:main.tex::\subsection{Skeleton-based Action Recognition Models}][3.2 Skeleton-based Action Recognition Models]]
*** [[file:main.tex::\subsection{Implementation][3.3 Implementation]]
*** [[file:main.tex::\subsection{Datasets}][3.4 Datasets]]
** [[file:main.tex::\section{Experiments}][4 Experiments]]
*** [[file:main.tex::\subsection{Evaluation Metrics}][4.1 Evaluation Metrics]]
*** [[file:main.tex::\subsection{Action Classification}][4.2 Action Classification]]
*** [[file:main.tex::\subsection{Action Anticipation}][4.3 Action Anticipation]]
*** [[file:main.tex::\subsection{Per-Class Performance Analysis}][4.4 Per-Class Performance Analysis]]
*** [[file:main.tex::\subsection{Performance and Implementation][4.5 Performance and Implementation Considerations]]
** [[file:main.tex::\section{Discussion and Conclusion}][5 Discussion and Conclusion]]
* Comments
** Review 648
- Show clearer position of novelty relative to existing pose-motion fusion methods
- Evaluation could be strengthened by including stronger baselines
- Deeper analysis of failure cases and robustness (e.g. to pose noise or global motion scenarios)
** Review 649
- Further clarify the difference between PoseOFF and existing joint-centred or pose-guided motion representations
- Provide more discussion as to why results show greater improvement for UCF101
- Clarify whether computational cost includes optical flow estimation or only model inference after feature extraction
- Increase figure resolution, increase fontsize, ensure figures will remain readable after being compressed into conference format
- Minor grammatical issues
** My responses
_RE: How PoseOFF differs from existing joint-centred motion scenarios:_ PoseOFF is designed to be a complementary motion representation to skeleton-keypoints. Other joint-centred motion representations, e.g. JOLO-GCN or H-MoRe, capture dense windows of optical flow that are learned in parallel with the skeleton representations. PoseOFF focuses on integrating these motion representations with existing skeleton-based action recognition models, allowing them to more rapidly anticipate human actions.
_RE: Deeper analysis of failure cases and robustness:_ There are some examples highlighted

* Keybinds
** Navigation
*** ] ] - org-next-visible-heading
Next heading
*** [ [ - org-previous-visible-heading
Previous heading
*** ] h - org-forward-heading-same-level
Next heading same level
*** [ h - org-backward-heading-same-level
Previous heading same level
*** g h - org-up-element
Move to upper (heading) element
*** z u - outline-up-heading
Backward to higher level heading
*** C-c C-j - org-goto
Jump to different place without changing the current outline visibility
** Visualising
*** z c - +org/close-fold
Folds current heading
*** z M - +org/close-all-folds
Folds all visual headings
** Correcting
*** ] s - +spell/next-error
Next ispell error
*** [ s - +spell/previous-error
Previous ispell error
** Table-of-contents
*** SPC m ; - reftex-toc
Open reftex table of contents for the entire document
*** TAB - reftex-toc-goto-line
Go to document location in other window, TOC window stays
*** f - reftex-toc-toggle-follow
Toggle follow (other LaTeX doc window follows with context)
*** r l - reftex-toc-rename-label
Rename the currently selected label in *toc* buffer
*** g O - reftex-toc-view-line
View document location in other window
*** J - reftex-toc-jump
Jump to specified section (e.g. '3 J' jumps to section 3)
*** < / > - reftex-toc-demote/promote
Demote or promote section or sections within selected region at point
* Searcher
Change ~search_string~ value to search for a particular string.
        e.g. ~search_string="flowpose"~
Change ~excluded_dirs~ to exclude particular directories from grep search.
        e.g. ~excluded_dirs=(":!./logs/*" ":!./org/*")~
#+begin_src bash :results output
## ----------------------
search_string="format"
excluded_dirs=(
    ":!./build/*"
    ":!./out/*"
    ":!./*.aux"
    ":!./*.log"
    ":!./*.toc"
    ":!./*.bbl"
    ":!./*.blg"
    ":!./*.fls"
    ":!./*.fdb_latexmk"
    ":!./*.synctex.gz"
    ":!./*.pdf"
    ":!./*.png"
    ":!./*.drawio"
    ":!./*.eps"
    ":!./.project-scratch.org"
)
## ----------------------

# Search for the file names
git grep -l $search_string -- ${excluded_dirs[@]}
# Provide a file count
echo -e "\nThere are $(git grep -l $search_string -- ${excluded_dirs[@]} | wc -l) files containing '${search_string}'"
#+end_src

#+RESULTS:
: IEEEbib.bst
: IEEEtran.cls
: README.org
: ieeeconf.cls
: main.tex
:
: There are 5 files containing 'format'

* Test bed
#+begin_src python :results output
print("Hello world!")
#+end_src

#+RESULTS:
: Hello world!
* Setup
Run the following codeblock to create a symlink to refs.bib when setting up this repo on a new machine.
**Replace the path below with your local =.bib= file location**
#+begin_src sh
## --------------------------
BIB_PATH="../refs.bib"
## --------------------------
ln -sf "$BIB_PATH" "$(dirname $0)/refs.bib"
echo "Symlink created → refs.bib"
#+end_src

#+RESULTS:
: Symlink created → refs.bib

* Refs Export
For publication, you may need to include a =.bib= file. You likely don't want ALL of the references included in there, so by running the codeblock below, it will override the symlink created in the [[Setup][setup]] above with *only* the references used in the latex file.
*NOTE:* This function parses the =.aux= file of the main latex file, so make sure to compile the LaTeX document before running the below codeblock!
*NOTE:* If a file called =refs.bib= already exists, it will create a save of the previous =refs.bib=, by apending the date and time to the end of the filename like: =refs.bib-save-2026.06.02:12.03.37=.
#+begin_src sh :results silent
# --------------------
main_filename="main"
# --------------------
bibexport -o refs.bib "${main_filename}.aux"
#+end_src

* TODOs
** Manual
*** General
- [ ] Ensure you run [[*Setup][Setup]] to copy the refs.bib!
** Scanner
Run scanner by moving cursor inside codeblock, then executing code =C-c C-c=
#+NAME: scan-todos
#+BEGIN_SRC emacs-lisp :results none
(require 'cl-lib)
(let* ((root (file-name-directory (buffer-file-name)))
       (extensions '(".py" ".js" ".ts" ".jsx" ".tsx"
                     ".rb" ".go" ".rs" ".java" ".c" ".cpp" ".h"
                     ".sh" ".bash" ".zsh" ".css" ".scss" ".html"
                     ".el" ".clj" ".ex" ".exs" ".md" ".org" ".tex"))
       (exclude-dirs '(".git" "node_modules" ".venv" "venv" "__pycache__"
                       "dist" "build" ".next" "target" "vendor"))
       (output ""))
  (dolist (file (directory-files-recursively root "."))
    (let ((rel (file-relative-name file root)))
      (when (and (cl-some (lambda (e) (string-suffix-p e file)) extensions)
                 (not (cl-some (lambda (d) (string-match-p (regexp-quote (concat "/" d "/")) (concat "/" rel))) exclude-dirs)))
        (with-temp-buffer
          (insert-file-contents file)
          (goto-char (point-min))
          (let (found)
            (while (re-search-forward "TODO:[[:space:]]*\\(.*\\)" nil t)
              (unless found
                (setq output (concat output (format "*** ~%s~\n" rel)))
                (setq found t))
              (setq output (concat output
                                   (format "    - Line %d: %s [[file:%s::%d][→]]\n"
                                           (line-number-at-pos)
                                           (string-trim (match-string 1))
                                           rel
                                           (line-number-at-pos))))))))))
  (save-excursion
    (goto-char (point-min))
    (when (re-search-forward "^\\*\\* Items$" nil t)
      (forward-line 1)
      (let ((start (point))
            (end (save-excursion
                   (if (re-search-forward "^\\*\\* " nil t)
                       (line-beginning-position)
                     (point-max)))))
        (delete-region start end)
        (insert "\n" (if (string-empty-p output) "   /No TODOs found./\n" output) "\n")))))
#+END_SRC
** Items

*** ~.project-scratch.org~
    - Line 173: [[:space:]]*\\(.*\\)" nil t) [[file:.project-scratch.org::173][→]]
*** ~main.tex~
    - Line 122: Stronger clarification here on differences between PoseOFF and existing joint-centred or pose-guided motion representations [[file:main.tex::122][→]]
