#+TITLE: ROMAN2026 presentation

- First, think about the structure of the talk itself
- Important that I show that I understand what other people have done, and understand where my talk fits
- There's no other talks in my block that uses optical flow - explain it!
- My approach has the advantage that it can be *easily added to skeleton based approaches*
- Follow up with Chris F to get one of his previous RO-MAN talks

* [[https://docs.google.com/presentation/d/1dB38sBbwjNxu_WONTpMKm5w7h4vHH46CrdlzaBDgoUY/edit?usp=sharing][DRIVE LINK]]
* Session title: Cognition, intent and embodied AI

* TODOS
- [ ] Go back to reviewer comments from RO-MAN and ICME and create question - answer slides based on the comments
** Formatting
- [ ] Check slide header and footer
  - Slide number
  - Swinburne logo
  - DSTG logo
  - Date
  - Conference details
- [ ] Remove the top part of the slide
- [ ] Make the slide numbers bigger
- [ ] Add my name and something else at footer
- [ ] Remove the extra stuff at the top of the slides...
- [ ] Utilise any dead space
- [ ] Get rid of highlighting altogether - replace with bold text
- [ ] Export finished presentation as PowerPoint and put on a USB

** Talk contents
- [ ] Slow down!
- [ ] Make it very clear what the aim is
  - Comparable or improved action recognition with fewer required frames
- [ ] Don't get bogged down in the biological inspiration (slide 7)
  - We are not modelling directly any biological system explicitly
  - If there's freebies at the conference that is iconic at the conference
- [ ] Classes where it does quite well are subtle movements show greatest improvement from poseoff

** Media generation
- [ ] Insert videos for the data types we're using (currently slide 6/9/10)
  - Skeleton pose video
  - Optical flow (RECREATE WITH THRESHOLDING + THICKER ARROWS)
- [ ] Provide a zoom in image of optical flow window/s after explaining PoseOFF
- [ ] Replace CNN with OURS in action anticipation graph in slide 14

** Media replacement
- [ ] Replace dataset example images
- [ ] Animate the benefits/drawbacks slide on PoseOFF

** Slide-by-slide
*** Slide 1:
- "The question we're interested in is how can we get low-cost, low latency human action recognition and the solution I'm going to present to you is called PoseOFF"
*** Slide 2:
- I could use the example of the person falling over
*** Slide 3:
- We are interested in vision as the sensory medium for enabling human robot interaction, due to low cost of implementation and passive nature as a sensory medium
- Fonts far too small - remove paper titles and just show the pictures
  - Show each example one by one
*** Slide 4:
- For the early visual motion cue section - the changing image gives a lot of very important and quickly availale information as to what is changing and can very quickly be fed into the anticipation of what is happening
*** Slide 5:
- Optical flow is one of the oldest problems in computer vision
- Put text description above each of vector fields
- When introducing optical flow:
  - "we're embedding motion cues spatiall sampled that we will show can indicate earlier what is happening"
*** Slide 6:
- Put the videos on a white background
*** Slide 7:
- Have each piece show up one by one
- Keep one consistent video (e.g. person falling over)
*** Slide 8:
- For slide 8 when I'm talking about how it's embedded, show a close up of three or so of the frame examples.
  - "By the third frame, the pose shows that the person could be about to run, but the flow field around the upper body keypoints indicates they are actually falling forward."
    - "We get more information earlier through these spatiotemporal patches that with pose alone"
    - "It is a targeted method that is lightweight and application focused, putting it where it needs to be to get the maximum benefit"
*** Slide 9:
- Could have the models come up one by one
- Grouping models by type:
  - /InfoGCN++/
    - Anticipation can we make it better?
  - /MS-G3D/ + /ST-GCN++/
    - Action recognition, can we get it to reason with fewer frames?
*** Slide 15 / 16 / 17
- In the datasets we chose, not all actions are realistic for human robot teaming, but we used them to benchmark our model
- For the kind of classes we're interested in, the PoseOFF embedded model performs well (if not as good, better)
- We also looked at class comparison etc.
*** Slide 18???
- Extraction time, data size, model complexity
*** LAST SLIDE
- Leave key findings up as last slide
- Add CADR-RAS funding as a logo...
- Key findings:
  - "Captures subtle..." Could be more specific



* Key points

- What are early visual motion cues?
  - How does the human vision system use them?
  - What is optical flow?
- What research is there on the extraction of early visual motion cues?


* Motivation

** Human Action Anticipation
The anticipation of human actions *BEFORE* they occur.


_Why it's important for HRI and HRT_

Early human action recognition is important for HRI and HRT.
    Timing and predictability of robot response play a critical role in interaction fluency.

Especially for highly autonomous systems - vision can be a primary sense modality that dictates how interactions occur.

[[https://inferensys.com/glossary/vision-language-action-models/human-robot-interaction/action-anticipation][See this website for more examples...]]
In the robotics space, human action anticipation has been shown to be effective for tasks such as:
- Human collaborative assembly
- Safe human-aware navigation
- Assitive robotics in elder care
- Interactive services and hospitality
- Surgical robotics and shared control
- Autonomous vehicle pedestrian interaction

** Current State
_How do we currently anticipate human actions in video?_

Skeleton representations are light and robust to background variation, but lack discriminative power to differentiate similar actions.
Dense motion representations (optical flow) captures rich motion information, at a computational cost.
Local, body-centred motion cues can retain informative dynamics with avoiding the cost of full-frame processing.

** How PoseOFF is different

Prior work has explored pose + flow...
    These rely on either parallel streams or global motion representations.
    No structuring motion features around human body dynamics.

* Early Visual Motion Cues

** What are they?

Cues that vision systems that we see in nature (human, animal, insect) 
Vision systems have evolved to detect these as they provide early information about motion within the visual scene.
These cues are important as motion may indicate changing environmental conditions.

** How does the human vision system use them?

In human contexts - when interacting with other humans - these early visual motion cues often convey information pertaining to action intent and emotional state.
Particularly salient for anticipating the actions of other people.

# Research on kinematic priming - the use of motion information encoded in movement kinematics - demonstrates that the human vision system can implicitly intuit intention based on movement kinematics.
# These findings are borne out in sports science research through the use of eye tracking data has shown that expert players attend to areas of an opponent’s body that are most salient to the action taking place.
# This highlights the importance of these early motion cues in rapidly assessing human actions.

** How can we detect them?

Early visual motion cues are spatially focused (REF).
Strategic sampling of motion patterns can highlight these early visual motion cues.

* What is optical flow, and how can we estimate it?

Estimation of the motion of pixels between image frames.

Optical flow can highlight motion patterns;
divergence, curl and shear of motion fields tell you about the movement and deformation of objects in the environment
- For example

Can capture rich spatiotemporal information which has been shown to improve action recognition and anticipation performance.

** How can we extract early visual motion cues?

* The gap filled by PoseOFF

These are sparse representations of human actions
Pros:
- Space efficient
- Impervious to background noise
Cons:
- Lack discriminative features
- Struggle to differentiate intra-class similarities

* Methods

** The PoseOFF Representation

** Skeleton-based Action Recognition Models

** Implementation
*** Pytorch
*** Datasets

* Results

** Action Classification

** Action Anticipation

** Per-Class Performance Analysis
