#+TITLE: ROMAN2026 presentation

- First, think about the structure of the talk itself
- Important that I show that I understand what other people have done, and understand where my talk fits
- There's no other talks in my block that uses optical flow - explain it!
- My approach has the advantage that it can be *easily added to skeleton based approaches*
- Follow up with Chris F to get one of his previous RO-MAN talks

* [[https://docs.google.com/presentation/d/1dB38sBbwjNxu_WONTpMKm5w7h4vHH46CrdlzaBDgoUY/edit?usp=sharing][DRIVE LINK]]
* Session title: Cognition, intent and embodied AI

* TODOS
- [ ] Check slide header and footer
  - Slide number
  - Swinburne logo
  - DSTG logo
  - Date
  - Conference details
- [ ] Make it very clear what the aim is
  - Comparable or improved action recognition with fewer required frames
- [ ] Don't get bogged down in the biological inspiration (slide 7)
  - We are not modelling directly any biological system explicitly
  - If there's freebies at the conference that is iconic at the conference
- [ ] Insert videos for the data types we're using (currently slide 11?)
  - Skeleton pose video
  - Optical flow
- [ ] Replace dataset example images
- [ ] Provide a zoom in image of optical flow window/s after explaining PoseOFF
- [ ] Animate the benefits/drawbacks slide on PoseOFF
- Classes where it does quite well are subtle movements show greatest improvement from poseoff


* Key points

- What are early visual motion cues?
  - How does the human vision system use them?
  - What is optical flow?
- What research is there on the extraction of early visual motion cues?


* Motivation

** Human Action Anticipation
The anticipation of human actions *BEFORE* they occur.


_Why it's important for HRI and HRT_

Early human action recognition is important for HRI and HRT.
    Timing and predictability of robot response play a critical role in interaction fluency.

Especially for highly autonomous systems - vision can be a primary sense modality that dictates how interactions occur.

[[https://inferensys.com/glossary/vision-language-action-models/human-robot-interaction/action-anticipation][See this website for more examples...]]
In the robotics space, human action anticipation has been shown to be effective for tasks such as:
- Human collaborative assembly
- Safe human-aware navigation
- Assitive robotics in elder care
- Interactive services and hospitality
- Surgical robotics and shared control
- Autonomous vehicle pedestrian interaction

** Current State
_How do we currently anticipate human actions in video?_

Skeleton representations are light and robust to background variation, but lack discriminative power to differentiate similar actions.
Dense motion representations (optical flow) captures rich motion information, at a computational cost.
Local, body-centred motion cues can retain informative dynamics with avoiding the cost of full-frame processing.

** How PoseOFF is different

Prior work has explored pose + flow...
    These rely on either parallel streams or global motion representations.
    No structuring motion features around human body dynamics.

* Early Visual Motion Cues

** What are they?

Cues that vision systems that we see in nature (human, animal, insect) 
Vision systems have evolved to detect these as they provide early information about motion within the visual scene.
These cues are important as motion may indicate changing environmental conditions.

** How does the human vision system use them?

In human contexts - when interacting with other humans - these early visual motion cues often convey information pertaining to action intent and emotional state.
Particularly salient for anticipating the actions of other people.

# Research on kinematic priming - the use of motion information encoded in movement kinematics - demonstrates that the human vision system can implicitly intuit intention based on movement kinematics.
# These findings are borne out in sports science research through the use of eye tracking data has shown that expert players attend to areas of an opponent’s body that are most salient to the action taking place.
# This highlights the importance of these early motion cues in rapidly assessing human actions.

** How can we detect them?

Early visual motion cues are spatially focused (REF).
Strategic sampling of motion patterns can highlight these early visual motion cues.

* What is optical flow, and how can we estimate it?

Estimation of the motion of pixels between image frames.

Optical flow can highlight motion patterns;
divergence, curl and shear of motion fields tell you about the movement and deformation of objects in the environment
- For example

Can capture rich spatiotemporal information which has been shown to improve action recognition and anticipation performance.

** How can we extract early visual motion cues?

* The gap filled by PoseOFF

These are sparse representations of human actions
Pros:
- Space efficient
- Impervious to background noise
Cons:
- Lack discriminative features
- Struggle to differentiate intra-class similarities

* Methods

** The PoseOFF Representation

** Skeleton-based Action Recognition Models

** Implementation
*** Pytorch
*** Datasets

* Results

** Action Classification

** Action Anticipation

** Per-Class Performance Analysis
