#+TITLE: ROMAN2026 presentation

 - First, think about the structure of the talk itself
 - Important that I show that I understand what other people have done, and understand where my talk fits
 - There's no other talks in my block that uses optical flow - explain it!
 - My approach has the advantage that it can be *easily added to skeleton based approaches*
 - Follow up with Chris F to get one of his previous RO-MAN talks

* Key points

- What are early visual motion cues?
  - How does the human vision system use them?
  - What is optical flow?
- What research is there on the extration of early visual motion cues?


* Motivation

Early human action recognition is important for HRI and HRT.
    Timing and predictability of robot response play a critical role in interaction fluency.
Skeleton representations are light and robust to background variation, but lack discriminative power to differentiate similar actions.
Dense motion representations (optical flow) captures rich motion information, at a computational cost.
Local, body-centred motion cues can retain informative dynamics with avoiding the cost of full-frame processing.

** How PoseOFF is different

Prior work has explored pose + flow...
    These rely on either parallel streams or global motion representations.
    No structuring motion features around human body dynamics.

* Early Visual Motion Cues

** What are they?

Cues that both human and animal vision systems have adapted to detect!
Vision systems have evolved to detect these as they provide early information about motion within the visual scene.
        These cues are important as motion - not caused by egomotion - may indicate changing environmental conditions.

** How does the human vision system use them?

Ego motion, detecting movement in the visual scene.
In human contexts, these early visual motion cues often convey information pertaining to action intent and emotional state.

* What is optical flow, and how can we estimate it?

Estimation of the motion of pixels between image frames.
Dense motion representations can capture rich spatiotemporal information which has been shown to improve action recognition performance.

Optical flow can highlight motion patterns;
divergence, curl and shear of motion fields tell you about the movement and deformation of objects in the environment
- For example

** How can we extract early visual motion cues?

* Action Recognition with Human Skeleton Keypoints

These are sparse representations of human actions
Pros:
- Space efficient
- Impervious to background noise
Cons:
- Lack discriminative features
- Struggle to differentiate intra-class similarities

* Methods

** The PoseOFF Representation

** Skeleton-based Action Recognition Models

** Implementation
*** Pytorch
*** Datasets

* Results

** Action Classification

** Action Anticipation

** Per-Class Performance Analysis
