#+TITLE: README
#+DESCRIPTION: README file for the PoseOFF paper


* Paper focus
- PoseOFF is:
  - Easy to implement
  - Lightweight
  - Improves action classification accuracy
  - Improves early action recognition accuracy
- Importantly, a way to embed human early visual motion cues to allow the model to predict actions with fewer frames!
- Defining local regions of flow so as to allow prediction models to both the movement of keypoints, as well as the relationship with other point-anchored patches.

* Core ideas
- PoseOFF as an extraction method can provide comparable accuracy with fewer observed frames
- Higher action anticipation ability with minimal additional computational overheads
** Action classification
This is retrospective recognition, where the full action is observed, and the action has already occured or is complete.
** Action anticipation
Prediction of an action classification label before the action has fully unfolded, using only partial observations.

* Refs.bib
You may need access to the refs.bib file to compile the LaTeX file. Let me know if you do, it's a very discorganised bib...

* Per-Class Accuracy Graphs
I've put all the graphs that I created for per-class accuracy improvement under =figures/Per_class_accuracy=. To get those results, I concatenated the action classes predicted for each model on the test split of the given dataset together, calculated the confusion matrix and obtained the per-class accuracy graphs from this.
e.g. (This is done separately for the Base and PoseOFF models)
#+begin_src python
# Arrays are of length ~16,000 for NTU60 (length of test split)
infogcn2_results = [3,1,2,3,4]
msg3d_results = [0,1,3,3,4]
stgcn2_results = [0,1,2,0,4]

ground_truth = [0,1,2,3,4]

# Concatenate arrays to create full truth/pred arrays for the given dataset
truth = np.concatenate([np.array(g) for i in range(3)]) # stack copies of ground truth...
pred = np.concatenate([infogcn2_results, msg3d_results, stgcn2_results])

# Create confusion matrix
confusion_matrix = confusion_matrix(truth, pred)

# Divide diagonal by sum of rows (recall) and columns (precision)
per_class_recall = confusion_matrix.diagonal() / confusion_matrix.sum(axis=1)
per_class_precision = confusion_matrix.diagonal() / confusion_matrix.sum(axis=0)
#+end_src

If can also provide the per-class improvement for each individual model, but there won't be enough space.

* TODO
- [ ] Per-class action graphs
  - [ ] Action recognition
  - [ ] Action anticipation
- [ ] Comparisons with first-order skeleton motion (joint displacement)
- [ ] Literature review - [[https://openaccess.thecvf.com/content/WACV2021/papers/Cai_JOLO-GCN_Mining_Joint-Centered_Light-Weight_Information_for_Skeleton-Based_Action_Recognition_WACV_2021_paper.pdf][JOLO-GCN paper]]
  - JOLO-GCN is fundamentally two-stream, PoseOFF is an embedding layer applied to existing skeleton-based action recognition backbones
